name: konami_detector
description: A package to detect your konami codes and executes the provided callbacks.
version: 1.0.0
homepage: https://github.com/Baseflow/konami_detector

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swipe_detector: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: